INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (1,'Aachen',' Germany');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (2,'Accra',' Ghana ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (3,'Adana',' Turkey ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (4,'Addis Ababa',' Ethiopia ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (5,'Adelaide',' Australia ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (6,'Agra',' India ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (7,'Ahmadabad','India ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (8,'Aleppo Syrian ','Arab Republic ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (9,'Alexandria ','Egypt ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (10,'Algiers ','Algeria ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (11,'Allahabad',' India');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (12,'Almaty ','Kazakhstan');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (13,'Amman ','Jordan ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (14,'Amritsar',' India ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (15,'Amsterdam',' Netherlands ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (16,'Ankara ','Turkey ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (17,'Anshan ','China ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (18,'Antananarivo',' Madagascar ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (19,'Asansol',' India ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (20,'Asuncion',' Paraguay ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (21,'Athens ','Greece ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (22,'Atlanta',' United States of America ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (23,'Auckland',' New Zealand ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (24,'Austin',' United States of America ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (25,'Baghdad ','Iraq ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (26,'Baixada Santista ','(Santos) Brazil ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (27,'Baku',' Azerbaijan ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (28,'Baltimore',' United States of America ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (29,'Bamako',' Mali ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (30,'Bandung ','Indonesia ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (31,'Bangalore',' India ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (32,'Bangkok ','Thailand ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (33,'Baotou ','China ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (34,'Barcelona ','Spain ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (35,'Barranquilla ','Colombia ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (36,'Basra',' Iraq ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (37,'Beihai ','China ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (38,'Beijing ','China ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (39,'Beirut ','Lebanon ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (40,'Belem','Brazil ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (41,'Belgrade ','Serbia and Montenegro ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (42,'Belo Horizonte ','Brazil ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (43,'Berlin ','Germany ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (44,'Bhopal ','India ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (45,'Bielefeld ','Germany ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (46,'Birmingham ','United Kingdom ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (47,'Boston ','United States of America ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (48,'Brazzaville ','Congo ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (49,'Brisbane ','Australia ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (50,'Bucaramanga',' Colombia ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (51,'Bucharest ','Romania ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (52,'Budapest ','Hungary ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (53,'Buenos Aires ','Argentina ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (54,'Bursa ','Turkey ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (55,'Cairo ','Egypt ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (56,'Calcutta ','India ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (57,'Calgary ','Canada ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (58,'Cali ','Colombia ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (59,'Campinas ','Brazil ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (60,'Cape Town ','South Africa ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (61,'Caracas ','Venezuela ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (62,'Casablanca',' Morocco ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (63,'Changchun ','China ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (64,'Changde ','China ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (65,'Changsha ','China ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (66,'Chelyabinsk ','Russian Federation ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (67,'Chengdu ','China ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (68,'Chennai ','(Madras) India ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (69,'Chicago ','United States of America ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (70,'Chifeng ','China ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (71,'Chittagong ','Bangladesh ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (72,'Chongqing ','China ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (73,'Cincinnati ','United States of America ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (74,'Ciudad Juarez ','Mexico ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (75,'Coimbatore',' India ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (76,'Columbus',' United States of America ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (77,'Conakry',' Guinea ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (78,'Copenhagen',' Denmark ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (79,'Cordoba ','Argentina ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (80,'Curitiba ','Brazil ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (81,'Dakar ','Senegal ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (82,'Dalian ','China ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (83,'Dallas','United States of America ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (84,'Damascus ','Syrian Arab Republic ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (85,'Daqing ','China ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (86,'Dar es Salaam ','United Republic of Tanzania ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (87,'Datong ','China ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (88,'Davao  ','Philippines');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (89,'Delhi  ','India ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (90,'Denver ','United States of America ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (91,'Detroit ','United States of America ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (92,'Dhaka ','Bangladesh ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (93,'Dhanbad ','India ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (94,'Dnepropetrovsk ','Ukraine ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (95,'Donetsk ','Ukraine ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (96,'Dongguan ','China ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (97,'Douala ','Cameroon ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (98,'Dublin',' Ireland ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (99,'Durban ','South Africa ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (100,'East Rand ','(Ekurhuleni) South Africa ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (101,'Ekaterinburg ','Russian Federation ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (102,'Esfahan ','Iran ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (103,'Faisalabad ','Pakistan ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (104,'Faridabad',' India ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (105,'Fortaleza ','Brazil ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (106,'Fukuoka-Kitakyushu ','Japan ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (107,'Fushun ','China ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (108,'Fuyu ','China ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (109,'Fuzhou',' Fujian China ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (110,'Ghaziabad ','India ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (111,'Guadalajara ','Mexico ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (112,'Guangzhou ','China ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (113,'Guayaquil  ','Ecuador');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (114,'Guiyang  ','China ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (115,'Gujranwala ','Pakistan ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (116,'Hai Phong ','Vietnam ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (117,'Hamburg ','Germany ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (118,'Handan ','China ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (119,'Hangzhou',' China ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (120,'Hannover ','Germany ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (121,'Hanoi ','Vietnam ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (122,'Harare ','Zimbabwe ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (123,'Harbin ','China ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (124,'Havana ','Cuba ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (125,'Hefei ','China ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (126,'Helsinki  ','Finland');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (127,'Heze ','China ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (128,'Ho Chi Minh ',' Vietnam ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (129,'Hong Kong ',' China');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (130,'Houston ','United States of America ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (131,'Huaian ','China ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (132,'Huainan ','China ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (133,'Huzhou ','China ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (134,'Hyderabad ','India ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (135,'Hyderabad ','Pakistan ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (136,'Ibadan ','Nigeria ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (137,'Indianapolis ','United States of America ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (138,'Indore ','India ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (139,'Istanbul ','Turkey ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (140,'Izmir ','Turkey ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (141,'Jabalpur ','India ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (142,'Jaipur ','India ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (143,'Jakarta ','Indonesia ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (144,'Jamshedpur ','India ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (145,'Jidda Saudi ','Arabia ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (146,'Jilin ','China ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (147,'Jinan ','China ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (148,'Jingmen ','China ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (149,'Jining',' China ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (150,'Jinxi ','China ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (151,'Johannesburg ','South Africa ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (152,'Kabul ','Afghanistan ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (153,'Kaduna ','Nigeria ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (154,'Kampala ','Uganda ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (155,'Kano ','Nigeria ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (156,'Kanpur ','India ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (157,'Kansas ','United States of America ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (158,'Kaohsiung ','China ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (159,'Karachi ','Pakistan ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (160,'Karaj ','Iran ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (161,'Katowice ','Poland ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (162,'Kazan ','Russian Federation ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (163,'Kharkov ',' Ukraine ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (164,'Khartoum ','Sudan ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (165,'Khulna ','Bangladesh ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (166,'Kiev ','Ukraine ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (167,'Kinshasa ','Dem. Rep. of the Congo ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (168,'Kochi ',' (Cochin) India');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (169,'Kuala Lumpur ','Malaysia ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (170,'Kunming ','China ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (171,'Kuwait ','Kuwait ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (172,'Kwangju ','Republic of Korea ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (173,'Kyoto ','Japan ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (174,'La Paz  ','Bolivia');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (175,'Lagos ','Nigeria ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (176,'Lahore ','Pakistan ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (177,'Lanzhou ','China ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (178,'Las Vegas ','United States of America ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (179,'Leeds ','United Kingdom ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (180,'Leshan ','China ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (181,'Lille  ','France');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (182,'Lima ','Peru ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (183,'Linyi ','China ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (184,'Lisbon ','Portugal ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (185,'Liuan ','China ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (186,'Liupanshui  ','China ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (187,'London ','United Kingdom ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (188,'Los Angeles ','United States of America ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (189,'Luanda ','Angola ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (190,'Lubumbashi ','Dem. Rep. of the Congo ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (191,'Lucknow ','India ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (192,'Ludhiana ','India ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (193,'Luoyang ','China ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (194,'Lusaka  ','Zambia');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (195,'Lyon ','France ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (196,'Madrid ','Spain ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (197,'Madurai  ','India ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (198,'Managua ','Nicaragua ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (199,'Manaus ','Brazil ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (200,'Manchester ','United Kingdom ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (201,'Maputo ','Mozambique ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (202,'Maracaibo ','Venezuela ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (203,'Maracay ','Venezuela ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (204,'Marseille-Aix-en-Provence',' France ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (205,'Mashhad ','Iran ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (206,'Mecca ','Saudi Arabia ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (207,'Medan ','Indonesia ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (208,'Medellin ','Colombia ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (209,'Meerut ','India ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (210,'Melbourne ','Australia ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (211,'Memphis ','United States of America ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (212,'Mendoza ','Argentina ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (213,'Metro Manila ','Philippines ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (214,'Mexico ','Mexico');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (215,'Miami ','United States of America ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (216,'Mianyang  ','China ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (217,'Milan ','Italy ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (218,'Milwaukee ','United States of America ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (219,'Minneapolis-St. Paul ','United States of America ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (220,'Minsk ','Belarus ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (221,'Mogadishu ','Somalia ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (222,'Monterrey ','Mexico ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (223,'Montevideo ','Uruguay ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (224,'Moscow ','Russian Federation ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (225,'Mosul ','Iraq ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (226,'Multan ','Pakistan ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (227,'Mumbai ','(Bombay) India ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (228,'Munich ','Germany ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (229,'Nagoya ','Japan ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (230,'Nagpur  ','India');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (231,'Nairobi ','Kenya ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (232,'Nanchang ','China ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (233,'Nanchong  ','China ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (234,'Nanjing ','China ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (235,'Nanning ','China ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (236,'Naples ','Italy ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (237,'Nashik',' India ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (238,'Neijiang ','China ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (239,'New Orleans ','United States of America ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (240,'New York ','United States of America ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (241,'Ningbo ','China ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (242,'Nizhni Novgorod ','Russian Federation ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (243,'Novosibirsk ','Russian Federation ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (244,'Nuremberg ','Germany ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (245,'Odessa ','Ukraine ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (246,'Omsk ','Russian Federation ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (247,'Orlando ','United States of America ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (248,'Osaka-Kobe ','Japan ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (249,'Ottawa ','Canada ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (250,'Palembang ','Indonesia ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (251,'Paris ','France ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (252,'Patna  ','India');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (253,'Perth ','Australia ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (254,'Peshawar ','Pakistan ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (255,'Philadelphia ','United States of America ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (256,'Phoenix-Mesa ','United States of America ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (257,'Pingxiang',' China ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (258,'Pittsburgh ','United States of America ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (259,'Port-au-Prince ','Haiti ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (260,'Portland ','United States of America ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (261,'Porto ','Portugal ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (262,'Prague ','Czech Republic ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (263,'Pretoria  ','South Africa ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (264,'Providence ','United States of America ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (265,'Puebla ','Mexico ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (266,'Pune ','(Poona) India ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (267,'Pusan ','Republic of Korea ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (268,'Pyongyang ','Dem. People Rep. of Korea ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (269,'Qingdao',' China ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (270,'Qiqihar ','China ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (271,'Quito ','Ecuador ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (272,'Rabat ','Morocco ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (273,'Rajkot',' India ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (274,'Rawalpindi ','Pakistan ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (275,'Recife ','Brazil ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (276,'Rhein-Main','Germany ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (277,'Rhein-Neckar ','Germany ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (278,'Rhein-Ruhr Middle ','Germany ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (279,'Rhein-Ruhr North ','Germany ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (280,'Rhein-Ruhr South','Germany');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (281,'Rio de Janeiro ','Brazil ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (282,'Riverside-San Bernardino ','United States of America ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (283,'Riyadh Saudi ','Arabia ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (284,'Rome ','Italy ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (285,'Rosario ','Argentina ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (286,'Rostov-on-Don ','Russian Federation ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (287,'Rotterdam ','Netherlands ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (288,'Sacramento ','United States of America ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (289,'Saint Petersburg ','Russian Federation ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (290,'Salvador',' Brazil ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (291,'Samara ','Russian Federation ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (292,'San Antonio ','United States of America ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (293,'San Diego ','United States of America ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (294,'San Francisco-Oakland ','United States of America ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (295,'San Jose',' United States of America ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (296,'San Juan ','Puerto Rico ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (297,'San Salvador ','El Salvador ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (298,'Sana a','Yemen ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (299,'Santa Cruz ','Bolivia ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (300,'Santiago ','Chile ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (301,'Santo Domingo ','Dominican Republic ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (302,'Sapporo ','Japan ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (303,'Seattle ','United States of America ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (304,'Seoul ','Republic of Korea ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (305,'Shanghai  ','China ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (306,'Shantou ','China ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (307,'Shenyang  ','China');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (308,'Shenzhen ','China ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (309,'Shijiazhuang ','China ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (310,'Shiraz ','Iran (Islamic Republic of) ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (311,'Singapore ','Singapore ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (312,'Sofia  ','Bulgaria');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (313,'Srinagar ','India ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (314,'St. Louis ','United States of America ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (315,'Stockholm ','Sweden ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (316,'Stuttgart ','Germany ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (317,'Suining ','China ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (318,'Suqian ','China ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (319,'Surabaja  ','Indonesia ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (320,'Surat ','India ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (321,'Suwon ','Republic of Korea ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (322,'Suzhou',' Jiangsu China ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (323,'Sydney',' Australia ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (324,'Tijuana','Mexico ');
INSERT INTO `ciudad` (`id`,`Ciudad`,`Zona`) VALUES (325,'Tokyo','Japan ');
